spring:
  application:
    name: configcrud
  servlet:
    multipart:
      max-request-size: 256MB
      max-file-size: 256MB
  datasource:
    url: replacewithenv
    username: replacewithenv
    password: replacewithenv
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select * from dual
      connection-pool-name: cserverConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: validate
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: 'true'
    show-sql: false
server:
   tomcat:
      connectionUploadTimeout: '600000'
      connection-timeout: '600000'
      max-swallow-size: 256MB
      connectionTimeout: '600000'
      max-http-form-post-size: 256MB
logging:
  level:
    oracle:
      spring:
        service: DEBUG
org:
  slf4j:
    simpleLogger:
      defaultLogLevel: debug

openai:
  key: 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